@startuml
skinparam linetype ortho

interface GameState {
    + executarAcao()
}

class JogoEmAndamento implements GameState
class JogoFinalizado implements GameState

class Jogo {
    - GameState estadoAtual
    + setEstado(GameState)
    + executarAcao()
}

Jogo --> GameState
JogoEmAndamento ..|> GameState
JogoFinalizado ..|> GameState

@enduml
