@startuml
skinparam linetype ortho

class MovePieceCommand {
    - Tabuleiro tabuleiro
    - Posicao origem
    - Posicao destino
    + MovePieceCommand(Tabuleiro, Posicao, Posicao)
    + execute()
    + undo()
}

@enduml
