@startuml
class Tabuleiro {
    -pecas: Peca[][]
    -pecasBrancas: int
    -pecasPretas: int
    +removerPeca(x: int, y: int)
}

class Peca {
    +getTime(): String
}

Tabuleiro --> "muitos" Peca : contém

' O Tabuleiro faz a verificação de vitória diretamente
note right of Tabuleiro
Verifica vitória/derrota
e imprime resultado
diretamente na lógica
do Tabuleiro.
end note

@enduml